mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('keti/', include('pybo.urls')), 
]

mysite/pybo/urls.py
from django.urls import path

from . import views

app_name = 'pybo'

urlpatterns = [
    path('', views.ChartView.as_view(),name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
    path('grid/', views.Home.as_view(), name='grid'),
    path('api/predict/', views.KospiPredictAPIView.as_view(), name="predict_kospi_api"),
    path('chart', views.index, name="chart"),
    path('SQL', views.SQLView.as_view(), name="SQL"),
]

mysite/pybo/models.py
from statistics import mode
from django.db import models

# Create your models here.
class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

class Query(models.Model):
    Query_ID = models.IntegerField()
    Full_Query = models.CharField(max_length=600)

class Work(models.Model):
    query = models.ForeignKey(Query, on_delete=models.CASCADE)
    Work_ID = models.IntegerField()
    Summary_Work = models.CharField(max_length=100)

class Metric(models.Model):
    work = models.ForeignKey(Work, on_delete=models.CASCADE)
    CSD_CPU = models.FloatField()
    SE_CPU = models.FloatField()
    DBC_CPU = models.FloatField()
    CSD_Memory = models.FloatField()
    SE_Memory = models.FloatField()
    DBC_Memory = models.FloatField()
    CSD_Power = models.FloatField()
    SE_Power = models.FloatField()
    DBC_Power = models.FloatField()
    CSD_Network = models.FloatField()
    SE_Network = models.FloatField()
    DBC_Network = models.FloatField()
    CSD_IO = models.FloatField()
    SE_IO = models.FloatField()
    DBC_IO = models.FloatField()
    CSD_Time = models.FloatField()
    SE_Time = models.FloatField()
    DBC_Time = models.FloatField()

class KospiPredict(models.Model):
    date = models.DateField("날짜", max_length=10, null=False, unique=True)
    close = models.FloatField("종가", null=True)
    open = models.FloatField("시가", null=True)
    # cate = (('aa','bb'),('dd','ee'))

mysite/pybo/forms.py
from django import forms
from pybo.models import Question, Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question  # 사용할 모델
        fields = ['subject', 'content']  # QuestionForm에서 사용할 Question 모델의 속성

        labels = {
            'subject': '제목',
            'content': '내용',
        }  

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

mysite/pybo/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Question, Answer, KospiPredict, Metric
from django.utils import timezone
from .forms import QuestionForm, AnswerForm
from django.http import HttpResponseNotAllowed
from django.core.paginator import Paginator  
from django.views.generic.base import TemplateView
from django.views.generic import View

from rest_framework.views import APIView
from rest_framework.response import Response
from time import mktime, strptime

def index(request):
    page = request.GET.get('page', '1')  # 페이지
    question_list = Question.objects.order_by('-create_date')
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj}
    return render(request, 'pybo/question_list.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)

def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        return HttpResponseNotAllowed('Only POST is possible.')
    context = {'question': question, 'form': form}
    return render(request, 'pybo/question_detail.html', context)

def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:index')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)


class Home(TemplateView):
    template_name = 'pybo/gridtest.html'


class KospiPredictAPIView(APIView):

    authentication_classes = []
    permission_classes = []

    def get(self, request):
        stocks = KospiPredict.objects.all().order_by('date')

        close_list = [1,2,3,4]
        open_list = [5,6,7,8,9]
        for stock in stocks:
            time_tuple = strptime(str(stock.date), '%Y-%m-%d')  
            utc_now = mktime(time_tuple) * 1000           
            close_list.append([utc_now, stock.close])
            open_list.append([utc_now, stock.open])

        data = {
            'close': close_list,
            'open': open_list
        }

        return Response(data)

class ChartView(View):
    def get(self, request, *args, **kwargs):
        metric = Metric.objects.all()
        context ={'metric': metric}
        return render(request, 'pybo/dashboard.html',context)


class base(View):
    def get(self, request, *args, **kwargs):
        context ={}
        return render(request, 'pybo/base.html',context)


class SQLView(View):
    def get(self, request, *args, **kwargs):
        context ={}
        return render(request, 'pybo/sql.html',context)

mysite/pybo/templates/pybo/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<style>
    /* Style the header with a grey background and some padding */
    .header {
        overflow: hidden;
        background-color: #f1f1f1;
        padding: 20px 10px;
    }

    /* Style the header links */
    .header a {
        float: left;
        color: black;
        text-align: center;
        padding: 12px;
        text-decoration: none;
        font-size: 18px;
        line-height: 25px;
        border-radius: 4px;
    }

    /* Style the logo link (notice that we set the same value of line-height and font-size to prevent the header to increase when the font gets bigger */
    .header a.logo {
        font-size: 25px;
        font-weight: bold;
    }

    /* Change the background color on mouse-over */
    .header a:hover {
        background-color: #ddd;
        color: black;
    }

    /* Style the active/current link*/
    .header a.active {
        background-color: dodgerblue;
        color: white;
    }

    /* Float the link section to the right */
    .header-right {
        float: right;
    }

    /* Add media queries for responsiveness - when the screen is 500px wide or less, stack the links on top of each other */
    @media screen and (max-width: 500px) {
        .header a {
            float: none;
            display: block;
            text-align: left;
        }

        .header-right {
            float: none;
        }

    }

    div.main {
        background: #f2f4f7;
    }

    .footer {
        position: fixed;
        left: 0;
        bottom: 0;
        height: auto;
        width: 100%;
        background-color: dimgray;
        color: white;
        text-align: center;
        overflow: hidden;
        padding: 20px 10px;
        z-index: 100;
    }

    .footer-left {
        float: left
    }

    .footer-right {
        float: right;
        margin-left: 10%;
    }

    .footer-centor {
        float: inline-start;
        margin-left: 10%;
    }

    .footer_li_txt {
        padding-left: 0;
        margin-bottom: 0.5rem;
    }

    .footer_li_txt li:first-child {
        border-left: 0;
        padding: 0 0.4rem 0 0;
    }

    .footer_li_txt li:nth-child(3):after {
        content: "\A";
        white-space: pre;
    }

    .footer_li_txt li {
        list-style: none;
        display: inline-block;
        font-size: 0.80rem;
        padding: 10 0.4rem 0 0.6rem;
        margin: 0;
        text-align: center;
        border-left: 1px solid rgb(0 0 0 / 10%);
        line-height: 0.8rem;
    }

    .footer_box_01 a {
        color: #8492a6 !important;
    }


    .footer a {
        float: none;
        display: block;
        text-align: left;
        padding: 12px;
        text-decoration: none;
        font-size: 18px;
        line-height: 25px;
        border-radius: 4px;
    }
    @media screen and (max-width: 500px) {
        .footer_li_txt{
            float: none;
            display: block;
        }
    }
</style>

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>KETI Database Monitor</title>
</head>
<div class="header">
    <a href="{% url 'pybo:index' %}" class="logo">KETI Database Monitor</a>
    <div class="header-right">
        <a class="active" href="#home">Home</a>
        <a href="#contact">Contact</a>
        <a href="#about">About</a>
    </div>
</div>
<div th:fragment="common-footer" class="footer">
    <div class="row">
      <div class="col footer_box_01">
        <ul class="footer_li_txt">
          <li>한국전자기술연구원</li>
          </script>
        </ul>
      </div>
    </div>

  </div>
  {% include "pybo/sidevar.html" %}
<body>


    <!-- 사이드바 -->


    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    <div class="main" style="background-color: #ffffff;">
        {% block content %}
        {% endblock %}
    </div>

    <!-- 기본 템플릿 안에 삽입될 내용 End -->
    <!-- Bootstrap JS -->
    <script src="{% static 'bootstrap.min.js' %}"></script>
</body>

</html>

mysite/pybo/templates/pybo/chart.html
<div class="main" id="container">
 
    <script src="https://code.highcharts.com/stock/highstock.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>
  
      function setChart() {
        Highcharts.setOption({
          global: {
            useUTC: false
          }
        });
      };
  
      $.ajax({
        url: "{% url 'pybo:predict_kospi_api' %}",
        dataType: 'json',
        success: function (data) {
  
          Highcharts.setOptions({
            global: {
              useUTC: false
            }
          });
  
          Highcharts.stockChart("container", {
  
            chart: {
              height: 500
            },
  
            title: { 
              text: '코스피 지수' 
            }, 
  
            rangeSelector: {
              selected: 5,
              inputEnabled: false
            },
  
            xAxis: {
              type: 'datetime',
              labels:{
                formatter: function(){
                  return Highcharts.dateFormat('%y.%m.%d', this.value);
                },
                step: 3
              }
            },
  
            yAxis: {
              labels: {
                format: '{value}p',
                style: {
                  color: 'rgba(0,0,0,.6)',
                },
                x: 30,
              },
              opposite: false,
              tickInterval: 50,   
            },
  
            tooltip: {
              xDateFormat: '%Y-%m-%d',
              split: true
            },
  
            series: [{
                name: '시가',          
                data: data.open,
                color: 'rgba(0,200,0,.6)',
                lineWidth: 2
            }, 
            {
                name: '종가',          
                data: data.close,
                lineWidth: 3
            }],
  
            legend: {
              enabled: true, 
              align: 'left',
              verticalAlign: 'top',
              floating: true,
              x: 30,
              y: 70
            },
            
            responsive: {
              rules: [{
                condition: {
                  maxWidth: 600
                },
                chartOptions: {
                  chart: {
                    height: 300
                  },
                  navigator: {
                    enabled: false
                  }
                }
              }]
            }
          });
        }
      });
  
    </script>
  </div>

mysite/pybo/templates/pybo/footer.html
<!DOCTYPE html>
<html lang="ko" 
xmlns:th="http://www.thymeleaf.org"
xmlns:sec="http://www.thymeleaf.org/extras/spring-security">

<head></head>
<body>

			
  <!-- Footer S -->
  <div th:fragment="common-footer" class="footer pt-5 pb-6" id="footer-main">
    <div class="row">
      <div class="col footer_box_01">
        <ul class="footer_li_txt">
          <li>에이팜스</li>
          <li>제주특별자치도 제주시 건입동 산지로 25 3F</li>
          <li>대표자 박기언</li>
          <li>통신판매업신고 2021-제주건입-0021</li>
          <li>사업자등록번호 127-94-74465</li>
          <li>afarms@afarms.ai</li>
          <li>FAX 02-312-0118</li>
          <li>TEL 02-312-0117</li>

          </script>
        </ul>
        <p class="text-sm mb-0">© 2021 <a href="/" class="h6 text-sm" target="_blank">Afarms</a>. All rights reserved.</p>
      </div>
      <!-- div class="col-sm-5 footer_box_02">
        <ul class="nav justify-content-center justify-content-md-end">
          <li class="nav-item">
            <a class="nav-link" href="#" data-toggle="modal" data-target=".terms-modal-sm">이용약관</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#" data-toggle="modal" data-target=".privacy-modal-sm">개인정보처리방침</a>
          </li>
        </ul>
      </div -->
    </div>

  </div>
  <!-- Footer E -->

  

      
</body>
</html>

mysite/pybo/templates/pybo/gridchart.html
{% extends 'pybo/base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="../contrast-bootstrap-pro/css/bootstrap.min.css" />
    <link rel="stylesheet" href="../contrast-bootstrap-pro/css/cdb.css" />
    <script src="../contrast-bootstrap-pro/js/cdb.js"></script>
    <script src="../contrast-bootstrap-pro/js/bootstrap.min.js"></script>
    <script src="https://kit.fontawesome.com/9d1d9a82d2.js" crossorigin="anonymous"></script>

    <title>How to create bootstrap charts using bootstrap 5</title>
</head>

<style>
    .wrapper {
        display: grid;
        grid-template-columns: repeat(3, 1fr);
        gap: 10px;
        grid-auto-rows: minmax(100px, auto);
    }

    .one {
        grid-column: 1 / 3;
        grid-row: 1;
    }

    .two {
        grid-column: 2 / 4;
        grid-row: 1 / 3;
    }

    .three {
        grid-column: 1;
        grid-row: 2 / 5;
    }

    .four {
        grid-column: 3;
        grid-row: 3;
    }

    .five {
        grid-column: 2;
        grid-row: 4;
    }

    .six {
        grid-column: 3;
        grid-row: 4;
    }

    .chart-container {
        width: 100%;
        height: 100%;
        margin: auto;
    }

    .chart-container a {
        padding: auto;
    }

    .chart-container a.one {
        grid-column: 3/ 7;
        grid-row: 3/7;
    }

    .chart-container a.two {
        grid-column: 3;
        grid-row: 1;
    }
    .chart-container a.three {
        grid-column: 1;
        grid-row: 2 / 5;
    }
</style>

<div class="wrapper">
    <div class="card chart-container">
        <a class="one">
            <canvas id="chart"></canvas>
        </a>
    </div>
    <div class="card chart-container">
        <a class="two">
            <canvas id="chart2"></canvas>
        </a>
    </div>
    <div class="card chart-container">
        <a class="two">
            <canvas id="chart3"></canvas>
        </a>
    </div>
    <div class="four">Four</div>
    <div class="five">Five</div>
    <div class="six">Six</div>
</div>
<script src="https://cdn.jsdelivr.net/npm/chart.js@3.7.1/dist/chart.min.js"></script>
<script>
    const ctx = document.getElementById("chart").getContext('2d');
    const myChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: ["sunday", "monday", "tuesday",
                "wednesday", "thursday", "friday", "saturday"],
            datasets: [{
                label: 'Last week',
                backgroundColor: 'rgba(161, 198, 247, 1)',
                borderColor: 'rgb(47, 128, 237)',
                data: [3000, 4000, 2000, 5000, 8000, 9000, 2000],
            }]
        },
        legend: {
            align: 'left'
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true,
                    }
                }]
            }
        },
    });
</script>
<script>
    const ctx2 = document.getElementById("chart2").getContext('2d');
    const myChart2 = new Chart(ctx2, {
        type: 'line',
        data: {
            labels: ["sunday", "monday", "tuesday",
                "wednesday", "thursday", "friday", "saturday"],
            datasets: [{
                label: 'Last week',
                backgroundColor: 'rgba(161, 198, 247, 1)',
                borderColor: 'rgb(47, 128, 237)',
                data: [3000, 4000, 2000, 5000, 8000, 9000, 100000],
            }]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true,
                    }
                }]
            }
        },
    });
</script>
<script>
    const ctx3 = document.getElementById("chart3").getContext('2d');
    const myChart3 = new Chart(ctx3, {
        type: 'line',
        data: {
            labels: ["sunday", "monday", "tuesday",
                "wednesday", "thursday", "friday", "saturday"],
            datasets: [{
                label: 'Last week',
                backgroundColor: 'rgba(161, 198, 247, 1)',
                borderColor: 'rgb(47, 128, 237)',
                data: [3000, 4000, 2000, 5000, 8000, 9000, 100000],
            }]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true,
                    }
                }]
            }
        },
    });
</script>

</html>
{% endblock %}

mysite/pybo/templates/pybo/gridtest.html
<!DOCTYPE html>
<style>

    body {
  display: grid;
  grid-gap: 0.2vw;
  height: 100vh;
  grid-template-columns: 150px 1fr;
  grid-template-rows: 120px 1fr 61px;
  grid-template-areas: "header   header"
                       "sidebar content"
                       "footer footer"; 
    }
    div.header {
    grid-area: header;
}
div.sidebar {
    grid-area: sidebar;
    background: #0769f3;
}
div.footer {
    grid-area: footer;
    background: #3581eb;
}
div.main {
    display: grid;  
    grid-gap: 0.2vw;
    grid-template-columns: repeat(auto-fill, minmax(150px, 1fr));
    grid-template-rows: repeat(auto-fill, minmax(150px, 1fr));
}
div.item{
    background-image: url('https://source.unsplash.com/daily');
}
div.main > div.item:nth-child(2)  { 
  grid-column: 2/span 5;
  grid-row: 1/span 2;
}
    </style>
    
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Django UI with CSS Grid Layout</title>
    </head>
<body>
<div class="header">
  <h1>Django UI with CSS Grid Layout</h1>
</div>

<div class="sidebar">
.sidebar
</div>

<div class="main">
<div class="item">
    <span>1</span>
</div>
<div class="item">
    <span>2</span>
</div>
<div class="item">
    <span>...</span>
</div>
<div class="item">
    <span>12</span>
</div>
</div>

<div class="footer">
Copyright 2018
</div>
</body>
</html>

mysite/pybo/templates/pybo/question_detail.html
{% extends 'pybo/base.html' %}
{% block content %}
<div class="container my-3">
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ question.create_date }}
                </div>
            </div>
        </div>
    </div>
    <!-- 답변 -->
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ answer.create_date }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- 답변 등록 -->
    <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}

mysite/pybo/templates/pybo/question_list.html
{% extends 'pybo/base.html' %}
{% load pybo_filter %}
{% block content %}
<div class="container main">
    <table class="table">
        <thead>
        <tr class="table-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr>
            <td>
                <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
            </td>

            <td>
                <a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a>
                {% if question.answer_set.count > 0 %}
                <span class="text-danger small mx-2">{{ question.answer_set.count }}</span>
                {% endif %}
            </td>
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
        <!-- 페이징처리 시작 -->
        <ul class="pagination justify-content-center">
            <!-- 이전페이지 -->
            {% if question_list.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ question_list.previous_page_number }}">이전</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
            </li>
            {% endif %}
            <!-- 페이지리스트 -->
            {% for page_number in question_list.paginator.page_range %}
            {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
            {% if page_number == question_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}

            {% endif %}
            {% endfor %}
            <!-- 다음페이지 -->
            {% if question_list.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ question_list.next_page_number }}">다음</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
            </li>
            {% endif %}
        </ul>
        <!-- 페이징처리 끝 -->
    <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">질문 등록하기</a>
</div>
{% endblock %}

mysite/pybo/templates/pybo/sidevar.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- CSS -->

    <title>SideBar sub menus</title>
</head>
<body id="body-pd">
    <div class="l-navbar" id="navbar">
        <nav class="nav">
            <div>
                <a class="navbar-brand" style="font-size: 20px;" href="{% url 'pybo:index' %}">KDM</a>
                <span class="nav_name" style="font-size: 10px; display: inline;">KETI</span>
                <button class="navbar-toggler" type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="nav__brand" >
                    <ion-icon name="menu-outline" class="nav__toggle" id="nav-toggle"></ion-icon>
                    <a href="#" class="nav__logo">KETI</a>
                </div>
                <div class="nav__list">
                    <a href="{% url 'pybo:index' %}" class="nav__link">
                        <ion-icon name="home-outline" class="nav__icon"></ion-icon>
                        <span class="nav_name">Dashboard</span>
                    </a>
                    <a href="{% url 'pybo:SQL' %}" class="nav__link">
                        <ion-icon name="chatbubbles-outline" class="nav__icon"></ion-icon>
                        <span class="nav_name">SQL</span>
                    </a>

                    <div href="#" class="nav__link collapse">
                        <ion-icon name="folder-outline" class="nav__icon"></ion-icon>
                        <span class="nav_name">Projects</span>

                        <ion-icon name="chevron-down-outline" class="collapse__link"></ion-icon>

                        <ul class="collapse__menu">
                            <a href="#" class="collapse__sublink">Data</a>
                            <a href="#" class="collapse__sublink">Group</a>
                            <a href="#" class="collapse__sublink">Members</a>
                        </ul>
                    </div>

                    <a href="#" class="nav__link">
                        <ion-icon name="pie-chart-outline" class="nav__icon"></ion-icon>
                        <span class="nav_name">Analytics</span>
                    </a>

                    <div href="#" class="nav__link collapse">
                        <ion-icon name="people-outline" class="nav__icon"></ion-icon>
                        <span class="nav_name">Team</span>

                        <ion-icon name="chevron-down-outline" class="collapse__link"></ion-icon>

                        <ul class="collapse__menu">
                            <a href="#" class="collapse__sublink">Data</a>
                            <a href="#" class="collapse__sublink">Group</a>
                            <a href="#" class="collapse__sublink">Members</a>
                        </ul>
                    </div>

                    <a href="#" class="nav__link">
                        <ion-icon name="settings-outline" class="nav__icon"></ion-icon>
                        <span class="nav_name">Settings</span>
                    </a>
                </div>
                <a href="#" class="nav__link">
                    <ion-icon name="log-out-outline" class="nav__icon"></ion-icon>
                    <span class="nav_name">Log out</span>
                </a>
            </div>
        </nav>
    </div>

    <!-- IONICONS -->
    <script src="https://unpkg.com/ionicons@5.2.3/dist/ionicons.js"></script>
    <!-- JS -->
    <!-- <script src="/mysite/pybo/static/main.js"></script> -->
    <script src="{% static 'main.js' %}"></script>
</body>
</html>