mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('keti/', include('pybo.urls')), 
]

mysite/polls/urls.py
from django.urls import path
from .views import ProductListAPI, DataListAPI, ContactFormView
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('api/product/', ProductListAPI.as_view()),
    path('api/', DataListAPI.as_view()),
    path('api/result/', views.ResultAPIView.as_view(), name="result_api"),
    path('result/', views.result_detail, name='result_detail'),
    path('api/predict/', views.KospiPredictAPIView.as_view(), name="predict_kospi_api"),
    path('chart', views.ChartView.as_view(), name="chart"),
    path('post', views.post_list, name="post"),
    path('post/new', views.post_new, name="post_new"),
    path('form', ContactFormView.as_view(), name="contact"),
    path('test', views.indextest, name='indextest'),
    path('board/', views.board, name='board'),
    path('home/', views.home, name='home'),
]

mysite/pybo/urls.py
from django.urls import path

from . import views

app_name = 'pybo'

urlpatterns = [
    path('', views.ChartView.as_view(),name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
    path('grid/', views.Home.as_view(), name='grid'),
    path('api/predict/', views.KospiPredictAPIView.as_view(), name="predict_kospi_api"),
    path('chart', views.index, name="chart"),
    path('SQL', views.SQLView.as_view(), name="SQL"),
]

mysite/polls/models.py
import datetime
from random import choices

from django.db import models
from django.utils import timezone
from django.contrib import admin
from django.conf import settings
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=20, unique=True)
    description = models.CharField(max_length=200, null=True, blank=True)
    has_answer = models.BooleanField(default=True)  # 답변가능 여부

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('polls:home', args=[self.name])


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Published recently?',
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)


class Product(models.Model):
    name = models.CharField(max_length=70)
    price = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Data(models.Model):
    specific_id = models.CharField('specific_id', max_length=156)
    horizon_width = models.CharField('horizon_width', max_length=100)
    vertical_width = models.CharField('vertical_width', max_length=100)
    x_location = models.CharField('x_location', max_length=100)
    y_location = models.CharField('y_location', max_length=100)
    def __str__(self):
        return str(self.specific_id)

class KospiPredict(models.Model):
    date = models.DateField("날짜", max_length=10, null=False, unique=True)
    close = models.FloatField("종가", null=True)
    open = models.FloatField("시가", null=True)
    # cate = (('aa','bb'),('dd','ee'))
    # catt = models.CharField(max_length = 10, choices = cate)

# Create your models here.


class TPC_H_QUERY(models.Model):
    query_id = models.IntegerField('queryid')
    work_id = models.IntegerField('workid')
    full_query = models.CharField('full_query', max_length=600)
    summary_work = models.CharField('summary_work', max_length=200)
    def __str__(self):
        return str(self.query_id)



class Side_Var(models.Model):
    seqnum = models.IntegerField('seqnum')
    name = models.CharField('fullname', max_length=100)
    def __str__(self):
        return str(self.seqnum)

mysite/polls/forms.py
from django import forms
from .models import Post

class SelectQueryForm(forms.Form):
    QUERY_1 = 'query_1'
    QUERY_2 = 'query_2'
    QUERY_3 = 'query_3'
    QUERY_4 = 'query_4'
    QUERY_5 = 'query_5'
    QUERY_6 = 'query_6'
    QUERY_7 = 'query_7'
    QUERY_8 = 'query_8'
    QUERY_9 = 'query_9'
    QUERY_10 = 'query_10'
    QUERY_11 = 'query_11'
    QUERY_12 = 'query_12'
    QUERY_13 = 'query_13'
    QUERY_14 = 'query_14'
    QUERY_15 = 'query_15'
    QUERY_16 = 'query_16'
    QUERY_17 = 'query_17'
    QUERY_18 = 'query_18'
    QUERY_19 = 'query_19'
    QUERY_20 = 'query_20'
    QUERY_21 = 'query_21'
    QUERY_22 = 'query_22'

    QUERY_CHOICES = (
        (QUERY_1, u"Query 1"),
        (QUERY_2, u"Query 2"),
        (QUERY_3, u"Query 3"),
        (QUERY_4, u"Query 4"),
        (QUERY_5, u"Query 5"),
        (QUERY_6, u"Query 6"),
        (QUERY_7, u"Query 7"),
        (QUERY_8, u"Query 8"),
        (QUERY_9, u"Query 9"),
        (QUERY_10, u"Query 10"),
        (QUERY_11, u"Query 11"),
        (QUERY_12, u"Query 12"),
        (QUERY_13, u"Query 13"),
        (QUERY_14, u"Query 14"),
        (QUERY_15, u"Query 15"),
        (QUERY_16, u"Query 16"),
        (QUERY_17, u"Query 17"),
        (QUERY_18, u"Query 18"),
        (QUERY_19, u"Query 19"),
        (QUERY_20, u"Query 20"),
        (QUERY_21, u"Query 21"),
        (QUERY_22, u"Query 22"),
    )
    querys = forms.ChoiceField(choices=QUERY_CHOICES)

    # def select_query(self,form):



class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)

mysite/polls/views.py
from urllib import request
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.views.generic import View
from django import forms
from django.views.generic.edit import FormView
from django.utils.functional import cached_property


from rest_framework.views import APIView
from .serializers import ProductSerializer, DataSerializer
from rest_framework.response import Response

from .models import Choice, Question, Product, Data, KospiPredict, Post, Side_Var
from .forms import SelectQueryForm

from time import mktime, strptime

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

# Create your views here.


class sidebarMixin(object): 
    @cached_property
    def getList(self):
        return Side_Var.objects.all()


class ContactFormView(FormView):
    template_name = 'polls/contact.html'
    form_class = SelectQueryForm
    success_url = '/thanks/'
    def get_query(request):
        if request.method == 'POST':
            print(request.method)
            pass
        else:
            print(request.method)
            pass
    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        form.send_email()
        return super().form_valid(form)

class KospiPredictAPIView(APIView):

    authentication_classes = []
    permission_classes = []

    def get(self, request):
        stocks = KospiPredict.objects.all().order_by('date')

        close_list = [1,2,3,4]
        open_list = [5,6,7,8,9]
        for stock in stocks:
            time_tuple = strptime(str(stock.date), '%Y-%m-%d')  
            utc_now = mktime(time_tuple) * 1000           
            close_list.append([utc_now, stock.close])
            open_list.append([utc_now, stock.open])

        data = {
            'close': close_list,
            'open': open_list
        }

        return Response(data)

class ChartView(sidebarMixin,View):
    def get(self, request, *args, **kwargs):
        context ={'sidebarList': Side_Var.objects.all()}
        return render(request, 'polls/home.html',context)



class ResultAPIView(APIView):
    
    authentication_classes = []
    permission_classes = []

    def get(self, request): 
        data = request.session.get('result')
        return Response(data)

def result_detail(request):

    context = {}
    return render(request, 'polls/chart.html', context )



class DataListAPI(APIView):
    def get(self, request):
        queryset = Data.objects.all()
        print(queryset)
        serializer = DataSerializer(queryset, many=True)
        return Response(serializer.data)

class ProductListAPI(APIView):
    def get(self, request):
        queryset = Product.objects.all()
        print(queryset)
        serializer = ProductSerializer(queryset, many=True)
        return Response(serializer.data)


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

# ...

def post_new(request):
    boards = Post.objects.all()
    context = {'object_list': boards}    
    return render(request, 'polls/head.html', context)

def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'polls/data_list.html', {'posts': posts})

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))




def indextest(request):
    return render(request, 'polls/indextest.html', {'title':'data'})

def home(request):
    return render(request, 'polls/home.html', {'title':'home'})    

def board(request):
    return render(request, 'polls/board.html', {'title':'board'})    




class CategoryView(View):
    template_name = 'polls/category.html'

    def get(self, request):
        context = {
            'categories': Category.objects.all(),
        }
        return render(request, self.template_name, context)

mysite/polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Demo{% endblock %}</title>
    <style>

        .topnav {
            top: 0;
            height: 60px;
            width: 100%;
            position: fixed;
            z-index:1;
            background-color:#02343F;
            overflow: hidden;
            display: flex;
            justify-content: center;
        }

        .topnav .center { 
            display:flex;
            align-items:center;
        }

        .topnav a {
            text-align: center;
            margin: 0px 5px 0px 5px;
        }

        a {
            color: #F0EDCC;
            text-decoration: none;
            font-size: 25px;
        }

        a:hover {
            color: white;
        }

        .sidemenu {
            height: 100%;
            width: 200px;
            position: fixed;
            z-index:1;
            top: 60px;
            left: 0;
            background-color:#02343F;
            overflow-x: hidden;
            padding-top: 20px;
        }

        .sidemenu li {
            margin:10px;
        }

        .wrap_content {
            margin-top: 70px;
            margin-left: 210px;
            margin-right: 10px;
        }

        ul {
            list-style:none;
            list-style-position: outside;
        }

        body {
            margin: 0px;
            background-color: #F0EDCC;
        }

    </style>
</head>
<body>

    <div class="topnav">
        <div class="center">
            <div class="menu">
                <a href="{% url 'polls:home' %}">Home</a>
                <a href="{% url 'polls:board' %}">Board</a>
            </div>
        </div>
    </div>

    <div class="sidemenu">
        <ul>
            <li><a href="{% url 'polls:home' %}">home</a></li>
            <li><a href="{% url 'polls:board' %}">board</a></li>
            <li><a href="#">menu3</a></li>
            <li><a href="#">menu4</a></li>
        <ul>
    </div>

    <div class="wrap_content">
        <div id="content" name="content" class="container">
        {% block content %}
        {% endblock %}
        </div>
    </div>

</body>
</html>

mysite/polls/templates/polls/chart.html
<div id="container">
 
    <script src="https://code.highcharts.com/stock/highstock.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>
  
      function setChart() {
        Highcharts.setOption({
          global: {
            useUTC: false
          }
        });
      };
  
      $.ajax({
        url: "{% url 'polls:predict_kospi_api' %}",
        dataType: 'json',
        success: function (data) {
  
          Highcharts.setOptions({
            global: {
              useUTC: false
            }
          });
  
          Highcharts.stockChart("container", {
  
            chart: {
              height: 500
            },
  
            title: { 
              text: '코스피 지수' 
            }, 
  
            rangeSelector: {
              selected: 5,
              inputEnabled: false
            },
  
            xAxis: {
              type: 'datetime',
              labels:{
                formatter: function(){
                  return Highcharts.dateFormat('%y.%m.%d', this.value);
                },
                step: 3
              }
            },
  
            yAxis: {
              labels: {
                format: '{value}p',
                style: {
                  color: 'rgba(0,0,0,.6)',
                },
                x: 30,
              },
              opposite: false,
              tickInterval: 50,   
            },
  
            tooltip: {
              xDateFormat: '%Y-%m-%d',
              split: true
            },
  
            series: [{
                name: '시가',          
                data: data.open,
                color: 'rgba(0,200,0,.6)',
                lineWidth: 2
            }, 
            {
                name: '종가',          
                data: data.close,
                lineWidth: 3
            }],
  
            legend: {
              enabled: true, 
              align: 'left',
              verticalAlign: 'top',
              floating: true,
              x: 30,
              y: 70
            },
            
            responsive: {
              rules: [{
                condition: {
                  maxWidth: 600
                },
                chartOptions: {
                  chart: {
                    height: 300
                  },
                  navigator: {
                    enabled: false
                  }
                }
              }]
            }
          });
        }
      });
  
    </script>
  </div>

mysite/polls/templates/polls/contact.html
<form method="get">{% csrf_token %}
    <div class="col-sm-3" style="float: left;margin-left: 10px; width: 20%;">쿼리 select {{ form.as_p }}
    <button method = "get" type="submit" class="btn btn-primary">불러오기</button>
    </div>
    <div class="col-sm-3" style="display: inline-block;"><header>Query</header><textarea disabled name="test" rows="20" cols="100">

    </textarea></div>
<!--     
    <input type="submit" value="Send message"> -->
</form>

<!-- <style>
.box1 {float:left; width:200px; height:100px; background-color:#234234;}
.box2 {display:inline-block; width:200px; height:100px; background-color:#666666; margin-left:10px;}
</style>
<body> 
    <div class="box1">

    </div> 
    <div class="box2">

    </div>
</body> -->

mysite/polls/templates/polls/data_list.html
<!-- {% extends 'polls/home.html' %} -->

<html>
    <body>
        <div class="test">
            <a href="{% url 'post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
            <h1><a href="/">Django Girls Blog</a></h1>
        </div>
    </body>
</html>

mysite/polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
    </form>

mysite/polls/templates/polls/footer.html
<div style = "text-align:center;margin-top:2px;">
    <div style="font-size:.6rem;">
        <span>공지사항</span> |
        <span>문의사항</span> |
        <span>서비스소개</span>
    </div>
    <div style="margin-top:1rem;">
        <h6>Hyunterest</h6>
    </div>

</div>

mysite/polls/templates/polls/head.html
<div style = "text-align:center; margin-bottom:2px;">
    <div>
        <h1>KETI DB Monitoring{{ question.question_text }}</h1>
    </div>
    <div class="test">
        <a href="{% url 'polls:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
        {% for post in object_list %}
        <h1><a href="/">{{post.author}}</a></h1>
        {% endfor %}
    </div>
    <div>
        <span>nav1</span>
        <span>nav2</span>
        <span>nav3</span>
        <span>nav4</span>
    </div>
</div>

mysite/polls/templates/polls/home.html
<!DOCTYPE html>
<html lang="ko">

    {% include 'polls/head.html' %}
    <body>
        {% include 'polls/contact.html' %}
        {% include 'polls/chart.html' %}

        {% include 'polls/footer.html' %}
    </body>
    
</html>

mysite/polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" href="{% static 'polls/style.css' %}">
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

mysite/polls/templates/polls/indextest.html
{% extends 'polls/base.html' %}

{% block title %}Index page{% endblock %}

{% block content %}
<style>
	.card {
		padding: 10px;		
	}

	.card h3 {
		font-family: none;
	}
</style>

<h2>Index Page</h2>

<div style="display:flex;">
	<div class="card" style="width:33%;">
		<h3>Django</h3>
		Django is a high-level Python Web framework that encourages rapid development and clean, pragmatic design. Built by experienced developers, it takes care of much of the hassle of Web development, so you can focus on writing your app without needing to reinvent the wheel. It’s free and open source.
	</div>

	<div class="card" style="width:33%;">
		<h3>Django</h3>
		Django is a high-level Python Web framework that encourages rapid development and clean, pragmatic design. Built by experienced developers, it takes care of much of the hassle of Web development, so you can focus on writing your app without needing to reinvent the wheel. It’s free and open source.
	</div>

	<div class="card" style="width:33%;">
		<h3>Django</h3>
		Django is a high-level Python Web framework that encourages rapid development and clean, pragmatic design. Built by experienced developers, it takes care of much of the hassle of Web development, so you can focus on writing your app without needing to reinvent the wheel. It’s free and open source.
	</div>
</div>
{% endblock  %}

mysite/polls/templates/polls/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'pybo:index' %}">KDM</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="#">로그인</a>
                </li>
            </ul>
        </div> -->
    </div>
</nav>

mysite/polls/templates/polls/result.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

mysite/polls/templates/polls/select.html
<form method="get" action="" class="form" style="margin-left: 7%; margin-top: 5%;">
    <select name="month" id="id_month">
      <option value="0" selected>월 선택</option>
      <option value="01">1월</option>
      <option value="02">2월</option>
      <option value="03">3월</option>
      <option value="04">4월</option>
      <option value="05">5월</option>
      <option value="06">6월</option>
      <option value="07">7월</option>
      <option value="08">8월</option>
      <option value="09">9월</option>
      <option value="10">10월</option>
      <option value="11">11월</option>
      <option value="12">12월</option>
    </select>
  </form>
  
  <script>
      $(document).ready(function() {
          $( "select[name=month]" ).val( "{{ month_text }}" );
          $('select[name=month]').change(function () {
          console.log($('select[name=month]').val());
          month = $('select[name=month]').val();
          $('.form').submit();
      });
  });
  </script>

mysite/polls/templates/polls/sidevar.html
<div class="container my-3">
    <div class="row">

        <div class="col-sm-12 col-md-3 col-lg-2 p-2">
<!-- Sidebar  -->
<nav id="sidebar" class="border-top border-secondary">
    <div class="list-group">
        {% for cat in category_list %}
            {% if cat == category %}
                <a class="rounded-0 list-group-item list-group-item-action list-group-item-light active"
                   href="{{ cat.get_absolute_url }}">{{ cat.description }}</a>
            {% else %}
                <a class="rounded-0 list-group-item list-group-item-action list-group-item-light"
                   href="{{ cat.get_absolute_url }}">{{ cat.description }}</a>
            {% endif %}
        {% endfor %}
    </div>
</nav>
        </div>

        <div class="col-sm-12 col-md-9 col-lg-10 p-2">
<!-- Content -->
<div id="content" class="border-top border-secondary">
    <div class="content_block">
    <h5 class="border-bottom pl-2 pb-3 my-2">{{ category.description }}</h5>
      
        <div class="row justify-content-between my-3">
        (... 기존 내용 ...)
        
        </div>
        (... 기존 내용 ...)
      
    </div>
</div>
        </div>
    </div>
</div>
      